In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


**ADDING DATA**


In [13]:
data=pd.read_csv('data.csv')
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [14]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
x,y
data.groupby('Country').sum("Sales")


Age    Salary
Country                 
France   164.0  276000.0
Germany  120.0  137000.0
Spain     65.0  161000.0

**REPLACING NAN or MISSING DATA**

In [15]:
# by interpolation
data.interpolate(method="cubic",inplace=False)

C:\Users\adity\AppData\Local\Temp\ipykernel_21012\1029365251.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate(method="cubic",inplace=False)


Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63787.255466       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  39.318449  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**one hotencoding to convert non-numererical data to vector**

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

__lable encoding__


In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**splitting the data in training and test**


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

**Feature Scaling**

In [22]:
import numpy as np
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])
x_train,x_test

(array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
        [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
        [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
        [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
        [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
        [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
        [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
        [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
       dtype=object),
 array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
        [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
       dtype=object))